apiVersion: batch/v1
kind: CronJob
metadata:
  name: detect-threats-cj
spec:
  # Define the schedule in Cron format, e.g., "*/5 * * * *" would be every 5 minutes
  schedule: "0 12 * * 5" # Every Friday at 12:00 PM
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: detect-threats-cj
              image: tbsacr.azurecr.io/detect-threats-cj:1.0.0 # Replace with your Docker image name and tag
              imagePullPolicy: Always # Always pull the image on job restart
          restartPolicy: OnFailure # Restart policy could be Always, OnFailure, or Never
