name: Deploy to AKS Cluster
on:
  push:
    branches:
      - master
    paths:
      - "src/detect_threats_and_email/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/detect_threats_and_email/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./scripts/decrypt_secrets.sh
        env:
          APPLICATION_SECRETS_PASSPHRASE: ${{ secrets.APPLICATION_SECRETS_PASSPHRASE }}

        # Add Python setup step if needed
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Your Python version

      - uses: Azure/docker-login@v1
        with:
          login-server: tbsacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build -f ./src/detect_threats_and_email/docker/Dockerfile . -t  tbsacr.azurecr.io/detect-threats-cj:${{ github.sha }}
          docker push tbsacr.azurecr.io/detect-threats-cj:${{ github.sha }}

      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: tbs-prod-aks
          resource-group: tbs-prod-rg

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            src/detect_threats_and_email/kubernetes/detect_threats_cronjob.yml
          images: |
            tbsacr.azurecr.io/detect-threats-cj:${{ github.sha }}
          namespace: |
            notify
